### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-tp2-visiteur-fougerouse-tp2#1]
Dand l'état ça vaut 0 sans le rapport.

Si vous n'avez pas eu le temps (souci perso ou autre) je suis pas devin, si vous me le dites pas je ne le sais pas. Hésitez pas à me contacter par mail dans ce cas

**Comment by Panderium** [comment]
Bonjour, je n'ai pas de soucis particulier merci, je mis suis un peu tard pour finir le TP :)

Je viens de push le rapport, je veux bien que vous y jetiez un œil si vous avez un peu de temps, je m'excuse du retard

**Comment by Panderium** [comment]
- J'ai construis deux package un pour les visitables un autre pour les visiteurs

- Un test avec 2 x 3 + 4 x 8 respect ne casse pas la priorité de la multiplication

- j'ai renommé getOpG, getOpD et getOp en getOperandeGauche, getOperandeDroit et getOperande 

- J'ai créé deux méthodes `printOperandeBinaire

**Comment by Slashgear** [comment]
- l'idée du printOperandeUnaire etc, ça part d'une bonne idée. Mais dans les fait, si tu as plein de type d'opération. Tu te retrouve avec plein de fonctions dans ton visiteurs abstrait. C'est pas ce qu'on cherche.
On devrait plutot dans ce cas surcharger les méthodes `toString` de ces opérations et les appeler directement.

Je ne te demande pas de le faire, mais n'hésite pas à me le dire si je ne suis pas clair 😉
